### Create a new user
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "User 1",
  "email": "j@j.com",
  "password": "123456"
}

### Genearate a token
POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
  "email": "j@j.com",
  "password": "123456"
}

